add_newline = false
format = """\
  $hostname\
  $git_branch\
  $git_state\
  $git_status\
  $directory\
  $character\
"""

[hostname]
format = "[$hostname]($style) "
ssh_only = false

[git_branch]
symbol = ""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
